# Generated by Django 5.0.6 on 2026-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('career_objective', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('programming_languages', models.TextField(blank=True)),
                ('web_frameworks', models.TextField(blank=True)),
                ('databases', models.TextField(blank=True)),
                ('tools', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('certificates', models.TextField(blank=True)),
                ('extracurricular', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('internship', models.TextField(blank=True)),
                ('languages_known', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
            ],
        ),
    ]
