# Generated by Django 6.0.4 on 2026-04-14 15:39

from django.db import migrations


def migrate_data(apps, schema_editor):
    Resume = apps.get_model('resume_app', 'Resume')
    Education = apps.get_model('resume_app', 'Education')
    Experience = apps.get_model('resume_app', 'Experience')

    for resume in Resume.objects.all():
        # --- Education Migration ---
        if resume.education:
            lines = [line.strip() for line in resume.education.splitlines() if line.strip()]
            temp = {}
            for line in lines:
                if line.startswith("College:"):
                    if temp:
                        Education.objects.create(resume=resume, **temp)
                        temp = {}
                    temp["institution"] = line.replace("College:", "").strip()
                elif line.startswith("Course:"):
                    temp["degree"] = line.replace("Course:", "").strip()
                elif line.startswith("Marks:"):
                    temp["marks"] = line.replace("Marks:", "").strip()
            if temp:
                # Ensure mandatory fields are not empty for the create call
                if "institution" not in temp: temp["institution"] = "Unknown"
                if "degree" not in temp: temp["degree"] = "Unknown"
                Education.objects.create(resume=resume, **temp)

        # --- Experience Migration (from Internships/Projects) ---
        # We'll treat each line in 'internship' as a separate Experience entry for now
        if resume.internship:
            lines = [line.strip() for line in resume.internship.splitlines() if line.strip()]
            for line in lines:
                Experience.objects.create(
                    resume=resume,
                    company="Legacy Internship",
                    role="Intern",
                    description=line
                )

def rollback_data(apps, schema_editor):
    Education = apps.get_model('resume_app', 'Education')
    Experience = apps.get_model('resume_app', 'Experience')
    Education.objects.all().delete()
    Experience.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_resume_experience_legacy_alter_resume_email_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, rollback_data),
    ]
