# Generated by Django 6.0.4 on 2026-04-14 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_migrate_legacy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_name',
            field=models.CharField(default='modern', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM-DD format', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Date must be in YYYY-MM-DD format', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
