# Generated by Django 6.0.4 on 2026-04-14 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_resume_template_name_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
